---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  chart:
    spec:
      chart: jupyterhub
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
      valuesFrom:
      - kind: ConfigMap
        name: values
        valuesKey: config.yaml
  interval: 1m0s