---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  chart:
    spec:
      chart: jupyterhub
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
  interval: 1m0s
  values:
    proxy:
      service:
        annotations:
          "alb.ingress.kubernetes.io/scheme": internet-facing
          "alb.ingress.kubernetes.io/target-type": ip
          "kubernetes.io/ingress.class": alb