
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cmfive-db-pvc
  namespace: cmfive
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi

