apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cmfive
  name: cmfive
  namespace: cmfive
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cmfive
  template:
    metadata:
      labels:
        app: cmfive
    spec:
      containers:
      - image: ghcr.io/2pisoftware/cmfive:dev
        name: cmfive
        env:
        - name: DB_HOST
          value: cmfive-db
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: cmfive
        - name: DB_USERNAME
          value: cmfive
        - name: DB_PASSWORD
          value: password
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
      - image: mysql
        name: cmfive-db
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: cmfive
        - name: MYSQL_USER
          value: cmfive
        - name: MYSQL_PASSWORD
          value: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: cmfive-db-storage
          mountPath: /var/lib/mysql
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
      imagePullSecrets:
      - name: ghcr-login-secret
    volumes:
    - name: cmfive-db-storage
      persistentVolumeClaim:
        claimName: cmfive-db-pvc
