apiVersion: v1
kind: Service
metadata:
  labels:
    app: cmfive
  name: cmfive
  namespace: cmfive
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: cmfive
  type: ClusterIP
