apiVersion: v1
kind: Service
metadata:
  labels:
    app: cmfive
  name: cmfive
  namespace: cmfive
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
    - port: 443
      protocol: TCP
      targetPort: 443
      name: https
  selector:
    app: cmfive
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb

