apiVersion: v1
kind: Service
metadata:
  labels:
    app: cmfive-db
  name: cmfive-db
  namespace: cmfive
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      name: mysql
  selector:
    app: cmfive-db
  type: ClusterIP

