apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodeodm
  name: nodeodm
  namespace: webodm
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: nodeodm
  type: LoadBalancer
