apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: webapp
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webapp
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/webodm-default: "true"
        io.kompose.service: webapp
    spec:
      containers:
        - command:
            - /bin/bash
            - -c
            - chmod +x /webodm/*.sh && /bin/bash -c "/webodm/wait-for-postgres.sh db /webodm/wait-for-it.sh -t 0 broker:6379 -- /webodm/start.sh"
          image: opendronemap/webodm_webapp
          name: webapp
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /webodm/app/media
              name: appmedia
      restartPolicy: Always
      volumes:
        - name: appmedia
          persistentVolumeClaim:
            claimName: appmedia
status: {}
