apiVersion: v1
kind: Service
metadata:
  labels:
    app: webodm
  name: webodm
  namespace: webodm
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: webodm
  type: LoadBalancer
