apiVersion: v1
kind: Service
metadata:
  labels:
    app: webodm-db
  name: webodm-db
  namespace: webodm
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: webodm-db
  type: ClusterIP
