
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: webodm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 10Gi

