FROM quay.io/toolbx-images/fedora-toolbox:40

# Install dnf packages
RUN dnf install -y \
    zsh \
    util-linux-user \
    git \
    wget \
    curl \
    which \
    nodejs npm \
    awscli \
    bat \
    micro \
    helm \
    gh

# Install AWS-CDK
RUN npm install -g aws-cdk

# Install FluxCD
RUN curl -s https://fluxcd.io/install.sh | bash

# Install Kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" &&\
    mv kubectl /usr/local/bin/kubectl &&\
    chmod +x /usr/local/bin/kubectl

# Install github.com/derailed/k9s
RUN dnf install -y https://github.com/derailed/k9s/releases/latest/download/k9s_linux_amd64.rpm

# Create user
RUN useradd -ms /bin/zsh dev

# Enable sudo access for dev
RUN echo "dev ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Change to dev
USER dev

# Install Oh My Zsh
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
COPY --chown=dev:dev .zshrc /home/dev/.zshrc

# Create ~/.local/bin and add it to PATH
RUN mkdir -p /home/dev/.local/bin
ENV PATH="/home/dev/.local/bin:${PATH}"

# Install kuztomize
RUN cd ~/.local/bin &&\
    curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

# Add kustomize zsh completions
RUN mkdir -p ~/.oh-my-zsh/completions &&\
    kustomize completion zsh > ~/.oh-my-zsh/completions/_kustomize

# Install kompose
RUN cd ~/.local/bin &&\
    curl -L https://github.com/kubernetes/kompose/releases/download/v1.31.2/kompose-linux-amd64 -o kompose &&\
    chmod +x kompose

WORKDIR /home/dev