---
apiVersion: helm.toolkit.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  chart:
    spec:
      chart: jupyterhub
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
  interval: 1m0s
# change the port to 8000
  values:
    proxy:
      service:
        ports:
          http:
            type: LoadBalancer
            nodePorts:
            http: 80
            https: 443